export const CARGO_LIST_REQUEST = 'CARGO_LIST_REQUEST';
export const CARGO_LIST_SUCCESS = 'CARGO_LIST_SUCCESS';
export const CARGO_LIST_FAIL = 'CARGO_LIST_FAIL';
export const CARGO_LIST_RESET = 'CARGO_LIST_RESET';

export const CARGO_ADD_REQUEST = 'CARGO_ADD_REQUEST';
export const CARGO_ADD_SUCCESS = 'CARGO_ADD_SUCCESS';
export const CARGO_ADD_FAIL = 'CARGO_ADD_FAIL';
export const CARGO_ADD_RESET = 'CARGO_ADD_RESET';

export const CARGO_DELETE_REQUEST = 'CARGO_DELETE_REQUEST';
export const CARGO_DELETE_SUCCESS = 'CARGO_DELETE_SUCCESS';
export const CARGO_DELETE_FAIL = 'CARGO_DELETE_FAIL';
export const CARGO_DELETE_RESET = 'CARGO_DELETE_RESET';

export const CARGO_DETAILS_REQUEST = 'CARGO_DETAILS_REQUEST';
export const CARGO_DETAILS_SUCCESS = 'CARGO_DETAILS_SUCCESS';
export const CARGO_DETAILS_FAIL = 'CARGO_DETAILS_FAIL';
export const CARGO_DETAILS_RESET = 'CARGO_DETAILS_RESET';

export const CARGO_EDIT_REQUEST = 'CARGO_EDIT_REQUEST';
export const CARGO_EDIT_SUCCESS = 'CARGO_EDIT_SUCCESS';
export const CARGO_EDIT_FAIL = 'CARGO_EDIT_FAIL';
export const CARGO_EDIT_RESET = 'CARGO_EDIT_RESET';