export const CATOCUP_LIST_REQUEST = 'CATOCUP_LIST_REQUEST';
export const CATOCUP_LIST_SUCCESS = 'CATOCUP_LIST_SUCCESS';
export const CATOCUP_LIST_FAIL = 'CATOCUP_LIST_FAIL';
export const CATOCUP_LIST_RESET = 'CATOCUP_LIST_RESET';

export const CATOCUP_ADD_REQUEST = 'CATOCUP_ADD_REQUEST';
export const CATOCUP_ADD_SUCCESS = 'CATOCUP_ADD_SUCCESS';
export const CATOCUP_ADD_FAIL = 'CATOCUP_ADD_FAIL';
export const CATOCUP_ADD_RESET = 'CATOCUP_ADD_RESET';

export const CATOCUP_DELETE_REQUEST = 'CATOCUP_DELETE_REQUEST';
export const CATOCUP_DELETE_SUCCESS = 'CATOCUP_DELETE_SUCCESS';
export const CATOCUP_DELETE_FAIL = 'CATOCUP_DELETE_FAIL';
export const CATOCUP_DELETE_RESET = 'CATOCUP_DELETE_RESET';

export const CATOCUP_DETAILS_REQUEST = 'CATOCUP_DETAILS_REQUEST';
export const CATOCUP_DETAILS_SUCCESS = 'CATOCUP_DETAILS_SUCCESS';
export const CATOCUP_DETAILS_FAIL = 'CATOCUP_DETAILS_FAIL';
export const CATOCUP_DETAILS_RESET = 'CATOCUP_DETAILS_RESET';

export const CATOCUP_EDIT_REQUEST = 'CATOCUP_EDIT_REQUEST';
export const CATOCUP_EDIT_SUCCESS = 'CATOCUP_EDIT_SUCCESS';
export const CATOCUP_EDIT_FAIL = 'CATOCUP_EDIT_FAIL';
export const CATOCUP_EDIT_RESET = 'CATOCUP_EDIT_RESET';