export const NUMBERS = {
  GET_DATA: "GET_DATA",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_ERROR: "DATA_ERROR",
  DATA_RESET: "DATA_RESET",
};


export const TRABXCLAS_DATA = "TRABXCLAS_DATA";
export const TRABXCLAS_SUCCESS = "TRABXCLAS_SUCCESS";
export const TRABXCLAS_ERROR = "TRABXCLAS_ERROR";
export const TRABXCLAS_RESET = "TRABXCLAS_RESET";



export const MUNXCLAS_DATA = "MUNXCLAS_DATA";
export const MUNXCLAS_SUCCESS = "MUNXCLAS_SUCCESS";
export const MUNXCLAS_ERROR = "MUNXCLAS_ERROR";
export const MUNXCLAS_RESET = "MUNXCLAS_RESET";

export const CATOCUPXTRAB_DATA = "CATOCUPXTRAB_DATA";
export const CATOCUPXTRAB_SUCCESS = "CATOCUPXTRAB_SUCCESS";
export const CATOCUPXTRAB_ERROR = "CATOCUPXTRAB_ERROR";
export const CATOCUPXTRAB_RESET = "CATOCUPXTRAB_RESET";

export const NIVPREPXTRAB_DATA = "NIVPREPXTRAB_DATA";
export const NIVPREPXTRAB_SUCCESS = "NIVPREPXTRAB_SUCCESS";
export const NIVPREPXTRAB_ERROR = "NIVPREPXTRAB_ERROR";
export const NIVPREPXTRAB_RESET = "NIVPREPXTRAB_RESET";

export const UNIDADORGXNIVPREP_DATA = "UNIDADORGXNIVPREP_DATA";
export const UNIDADORGXNIVPREP_SUCCESS = "UNIDADORGXNIVPREP_SUCCESS";
export const UNIDADORGXNIVPREP_ERROR = "UNIDADORGXNIVPREP_ERROR";
export const UNIDADORGXNIVPREP_RESET = "UNIDADORGXNIVPREP_RESET";
