export const FUENTEPROCEDENCIA_LIST_REQUEST = 'FUENTEPROCEDENCIA_LIST_REQUEST';
export const FUENTEPROCEDENCIA_LIST_SUCCESS = 'FUENTEPROCEDENCIA_LIST_SUCCESS';
export const FUENTEPROCEDENCIA_LIST_FAIL = 'FUENTEPROCEDENCIA_LIST_FAIL';
export const FUENTEPROCEDENCIA_LIST_RESET = 'FUENTEPROCEDENCIA_LIST_RESET';

export const FUENTEPROCEDENCIA_ADD_REQUEST = 'FUENTEPROCEDENCIA_ADD_REQUEST';
export const FUENTEPROCEDENCIA_ADD_SUCCESS = 'FUENTEPROCEDENCIA_ADD_SUCCESS';
export const FUENTEPROCEDENCIA_ADD_FAIL = 'FUENTEPROCEDENCIA_ADD_FAIL';
export const FUENTEPROCEDENCIA_ADD_RESET = 'FUENTEPROCEDENCIA_ADD_RESET';

export const FUENTEPROCEDENCIA_DELETE_REQUEST = 'FUENTEPROCEDENCIA_DELETE_REQUEST';
export const FUENTEPROCEDENCIA_DELETE_SUCCESS = 'FUENTEPROCEDENCIA_DELETE_SUCCESS';
export const FUENTEPROCEDENCIA_DELETE_FAIL = 'FUENTEPROCEDENCIA_DELETE_FAIL';
export const FUENTEPROCEDENCIA_DELETE_RESET = 'FUENTEPROCEDENCIA_DELETE_RESET';

export const FUENTEPROCEDENCIA_DETAILS_REQUEST = 'FUENTEPROCEDENCIA_DETAILS_REQUEST';
export const FUENTEPROCEDENCIA_DETAILS_SUCCESS = 'FUENTEPROCEDENCIA_DETAILS_SUCCESS';
export const FUENTEPROCEDENCIA_DETAILS_FAIL = 'FUENTEPROCEDENCIA_DETAILS_FAIL';
export const FUENTEPROCEDENCIA_DETAILS_RESET = 'FUENTEPROCEDENCIA_DETAILS_RESET';

export const FUENTEPROCEDENCIA_EDIT_REQUEST = 'FUENTEPROCEDENCIA_EDIT_REQUEST';
export const FUENTEPROCEDENCIA_EDIT_SUCCESS = 'FUENTEPROCEDENCIA_EDIT_SUCCESS';
export const FUENTEPROCEDENCIA_EDIT_FAIL = 'FUENTEPROCEDENCIA_EDIT_FAIL';
export const FUENTEPROCEDENCIA_EDIT_RESET = 'FUENTEPROCEDENCIA_EDIT_RESET';