export const GRUPOESCALA_LIST_REQUEST = 'GRUPOESCALA_LIST_REQUEST';
export const GRUPOESCALA_LIST_SUCCESS = 'GRUPOESCALA_LIST_SUCCESS';
export const GRUPOESCALA_LIST_FAIL = 'GRUPOESCALA_LIST_FAIL';
export const GRUPOESCALA_LIST_RESET = 'GRUPOESCALA_LIST_RESET';
export const GRUPOESCALA_ADD_REQUEST = 'GRUPOESCALA_ADD_REQUEST';
export const GRUPOESCALA_ADD_SUCCESS = 'GRUPOESCALA_ADD_SUCCESS';
export const GRUPOESCALA_ADD_FAIL = 'GRUPOESCALA_ADD_FAIL';
export const GRUPOESCALA_ADD_RESET = 'GRUPOESCALA_ADD_RESET';

export const GRUPOESCALA_DELETE_REQUEST = 'GRUPOESCALA_DELETE_REQUEST';
export const GRUPOESCALA_DELETE_SUCCESS = 'GRUPOESCALA_DELETE_SUCCESS';
export const GRUPOESCALA_DELETE_FAIL = 'GRUPOESCALA_DELETE_FAIL';
export const GRUPOESCALA_DELETE_RESET = 'GRUPOESCALA_DELETE_RESET';

export const GRUPOESCALA_DETAILS_REQUEST = 'GRUPOESCALA_DETAILS_REQUEST';
export const GRUPOESCALA_DETAILS_SUCCESS = 'GRUPOESCALA_DETAILS_SUCCESS';
export const GRUPOESCALA_DETAILS_FAIL = 'GRUPOESCALA_DETAILS_FAIL';
export const GRUPOESCALA_DETAILS_RESET = 'GRUPOESCALA_DETAILS_RESET';

export const GRUPOESCALA_EDIT_REQUEST = 'GRUPOESCALA_EDIT_REQUEST';
export const GRUPOESCALA_EDIT_SUCCESS = 'GRUPOESCALA_EDIT_SUCCESS';
export const GRUPOESCALA_EDIT_FAIL = 'GRUPOESCALA_EDIT_FAIL';
export const GRUPOESCALA_EDIT_RESET = 'GRUPOESCALA_EDIT_RESET';