export const MOTIVOBAJA_LIST_REQUEST = 'MOTIVOBAJA_LIST_REQUEST';
export const MOTIVOBAJA_LIST_SUCCESS = 'MOTIVOBAJA_LIST_SUCCESS';
export const MOTIVOBAJA_LIST_FAIL = 'MOTIVOBAJA_LIST_FAIL';
export const MOTIVOBAJA_LIST_RESET = 'MOTIVOBAJA_LIST_RESET';

export const MOTIVOBAJA_ADD_REQUEST = 'MOTIVOBAJA_ADD_REQUEST';
export const MOTIVOBAJA_ADD_SUCCESS = 'MOTIVOBAJAADD_SUCCESS';
export const MOTIVOBAJA_ADD_FAIL = 'MOTIVOBAJA_ADD_FAIL';
export const MOTIVOBAJA_ADD_RESET = 'MOTIVOBAJA_ADD_RESET';

export const MOTIVOBAJA_DELETE_REQUEST = 'MOTIVOBAJA_DELETE_REQUEST';
export const MOTIVOBAJA_DELETE_SUCCESS = 'MOTIVOBAJA_DELETE_SUCCESS';
export const MOTIVOBAJA_DELETE_FAIL = 'MOTIVOBAJA_DELETE_FAIL';
export const MOTIVOBAJA_DELETE_RESET = 'MOTIVOBAJA_DELETE_RESET';

export const MOTIVOBAJA_DETAILS_REQUEST = 'MOTIVOBAJA_DETAILS_REQUEST';
export const MOTIVOBAJA_DETAILS_SUCCESS = 'MOTIVOBAJA_DETAILS_SUCCESS';
export const MOTIVOBAJA_DETAILS_FAIL = 'MOTIVOBAJA_DETAILS_FAIL';
export const MOTIVOBAJA_DETAILS_RESET = 'MOTIVOBAJA_DETAILS_RESET';

export const MOTIVOBAJA_EDIT_REQUEST = 'MOTIVOBAJA_EDIT_REQUEST';
export const MOTIVOBAJA_EDIT_SUCCESS = 'MOTIVOBAJA_EDIT_SUCCESS';
export const MOTIVOBAJA_EDIT_FAIL = 'MOTIVOBAJA_EDIT_FAIL';
export const MOTIVOBAJA_EDIT_RESET = 'MOTIVOBAJA_EDIT_RESET';