export const NIVELPREPARACION_LIST_REQUEST = 'NIVELPREPARACION_LIST_REQUEST';
export const NIVELPREPARACION_LIST_SUCCESS = 'NIVELPREPARACION_LIST_SUCCESS';
export const NIVELPREPARACION_LIST_FAIL = 'NIVELPREPARACION_LIST_FAIL';
export const NIVELPREPARACION_LIST_RESET = 'NIVELPREPARACION_LIST_RESET';

export const NIVELPREPARACION_ADD_REQUEST = 'NIVELPREPARACION_ADD_REQUEST';
export const NIVELPREPARACION_ADD_SUCCESS = 'NIVELPREPARACION_ADD_SUCCESS';
export const NIVELPREPARACION_ADD_FAIL = 'NIVELPREPARACION_ADD_FAIL';
export const NIVELPREPARACION_ADD_RESET = 'NIVELPREPARACION_ADD_RESET';

export const NIVELPREPARACION_DELETE_REQUEST = 'NIVELPREPARACION_DELETE_REQUEST';
export const NIVELPREPARACION_DELETE_SUCCESS = 'NIVELPREPARACION_DELETE_SUCCESS';
export const NIVELPREPARACION_DELETE_FAIL = 'NIVELPREPARACION_DELETE_FAIL';
export const NIVELPREPARACION_DELETE_RESET = 'NIVELPREPARACION_DELETE_RESET';

export const NIVELPREPARACION_DETAILS_REQUEST = 'NIVELPREPARACION_DETAILS_REQUEST';
export const NIVELPREPARACION_DETAILS_SUCCESS = 'NIVELPREPARACION_DETAILS_SUCCESS';
export const NIVELPREPARACION_DETAILS_FAIL = 'NIVELPREPARACION_DETAILS_FAIL';
export const NIVELPREPARACION_DETAILS_RESET = 'NIVELPREPARACION_DETAILS_RESET';

export const NIVELPREPARACION_EDIT_REQUEST = 'NIVELPREPARACION_EDIT_REQUEST';
export const NIVELPREPARACION_EDIT_SUCCESS = 'NIVELPREPARACION_EDIT_SUCCESS';
export const NIVELPREPARACION_EDIT_FAIL = 'NIVELPREPARACION_EDIT_FAIL';
export const NIVELPREPARACION_EDIT_RESET = 'NIVELPREPARACION_EDIT_RESET';