export const OBJECT_LIST_REQUEST = 'OBJECT_LIST_REQUEST';
export const OBJECT_LIST_SUCCESS = 'OBJECT_LIST_SUCCESS';
export const OBJECT_LIST_FAIL = 'OBJECT_LIST_FAIL';
export const OBJECT_LIST_RESET = 'OBJECT_LIST_RESET';

export const OBJECT_ADD_REQUEST = 'OBJECT_ADD_REQUEST';
export const OBJECT_ADD_SUCCESS = 'OBJECT_ADD_SUCCESS';
export const OBJECT_ADD_FAIL = 'OBJECT_ADD_FAIL';
export const OBJECT_ADD_RESET = 'OBJECT_ADD_RESET';

export const OBJECT_DELETE_REQUEST = 'OBJECT_DELETE_REQUEST';
export const OBJECT_DELETE_SUCCESS = 'OBJECT_DELETE_SUCCESS';
export const OBJECT_DELETE_FAIL = 'OBJECT_DELETE_FAIL';
export const OBJECT_DELETE_RESET = 'OBJECT_DELETE_RESET';

export const OBJECT_DETAILS_REQUEST = 'OBJECT_DETAILS_REQUEST';
export const OBJECT_DETAILS_SUCCESS = 'OBJECT_DETAILS_SUCCESS';
export const OBJECT_DETAILS_FAIL = 'OBJECT_DETAILS_FAIL';
export const OBJECT_DETAILS_RESET = 'OBJECT_DETAILS_RESET';

export const OBJECT_EDIT_REQUEST = 'OBJECT_EDIT_REQUEST';
export const OBJECT_EDIT_SUCCESS = 'OBJECT_EDIT_SUCCESS';
export const OBJECT_EDIT_FAIL = 'OBJECT_EDIT_FAIL';
export const OBJECT_EDIT_RESET = 'OBJECT_EDIT_RESET';