export const PLAZA_LIST_REQUEST = 'PLAZA_LIST_REQUEST';
export const PLAZA_LIST_SUCCESS = 'PLAZA_LIST_SUCCESS';
export const PLAZA_LIST_FAIL = 'PLAZA_LIST_FAIL';
export const PLAZA_LIST_RESET = 'PLAZA_LIST_RESET';

export const PLAZA_ADD_REQUEST = 'PLAZA_ADD_REQUEST';
export const PLAZA_ADD_SUCCESS = 'PLAZA_ADD_SUCCESS';
export const PLAZA_ADD_FAIL = 'PLAZA_ADD_FAIL';
export const PLAZA_ADD_RESET = 'PLAZA_ADD_RESET';

export const PLAZA_DELETE_REQUEST = 'PLAZA_DELETE_REQUEST';
export const PLAZA_DELETE_SUCCESS = 'PLAZA_DELETE_SUCCESS';
export const PLAZA_DELETE_FAIL = 'PLAZA_DELETE_FAIL';
export const PLAZA_DELETE_RESET = 'PLAZA_DELETE_RESET';

export const PLAZA_DETAILS_REQUEST = 'PLAZA_DETAILS_REQUEST';
export const PLAZA_DETAILS_SUCCESS = 'PLAZA_DETAILS_SUCCESS';
export const PLAZA_DETAILS_FAIL = 'PLAZA_DETAILS_FAIL';
export const PLAZA_DETAILS_RESET = 'PLAZA_DETAILS_RESET';

export const PLAZA_EDIT_REQUEST = 'PLAZA_EDIT_REQUEST';
export const PLAZA_EDIT_SUCCESS = 'PLAZA_EDIT_SUCCESS';
export const PLAZA_EDIT_FAIL = 'PLAZA_EDIT_FAIL';
export const PLAZA_EDIT_RESET = 'PLAZA_EDIT_RESET';