export const PROVINCE_LIST_REQUEST = 'PROVINCE_LIST_REQUEST';
export const PROVINCE_LIST_SUCCESS = 'PROVINCE_LIST_SUCCESS';
export const PROVINCE_LIST_FAIL = 'PROVINCE_LIST_FAIL';
export const PROVINCE_LIST_RESET = 'PROVINCE_LIST_RESET';
export const PROVINCE_ADD_REQUEST = 'PROVINCE_ADD_REQUEST';
export const PROVINCE_ADD_SUCCESS = 'PROVINCE_ADD_SUCCESS';
export const PROVINCE_ADD_FAIL = 'PROVINCE_ADD_FAIL';
export const PROVINCE_ADD_RESET = 'PROVINCE_ADD_RESET';

export const PROVINCE_DELETE_REQUEST = 'PROVINCE_DELETE_REQUEST';
export const PROVINCE_DELETE_SUCCESS = 'PROVINCE_DELETE_SUCCESS';
export const PROVINCE_DELETE_FAIL = 'PROVINCE_DELETE_FAIL';
export const PROVINCE_DELETE_RESET = 'PROVINCE_DELETE_RESET';

export const PROVINCE_DETAILS_REQUEST = 'PROVINCE_DETAILS_REQUEST';
export const PROVINCE_DETAILS_SUCCESS = 'PROVINCE_DETAILS_SUCCESS';
export const PROVINCE_DETAILS_FAIL = 'PROVINCE_DETAILS_FAIL';
export const PROVINCE_DETAILS_RESET = 'PROVINCE_DETAILS_RESET';

export const PROVINCE_EDIT_REQUEST = 'PROVINCE_EDIT_REQUEST';
export const PROVINCE_EDIT_SUCCESS = 'PROVINCE_EDIT_SUCCESS';
export const PROVINCE_EDIT_FAIL = 'PROVINCE_EDIT_FAIL';
export const PROVINCE_EDIT_RESET = 'PROVINCE_EDIT_RESET';